FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY logo.png /usr/share/nginx/html/logo.png
COPY privacidade /usr/share/nginx/html/privacidade
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
